"""
signal.py - Signal Generator for BTC-Leads Strategy.
Analyzes BTC 1H candles to detect >1% triggers and generates trading signals.
"""
from datetime import datetime, timezone, timedelta
from typing import Optional

from backend.config import (
    BTC_TRIGGER_PCT, TP_PCT, SL_PCT, WINDOW_BARS,
    POSITION_SIZE_USDT, MAX_COINS_PER_TRADE,
    FIXED_COINS, to_ist_timestamp,
)
from backend.api.binance import get_data_client
from backend.database.db import mark_candle_processed, is_candle_processed, log_event
from backend.state.state_manager import (
    PositionState, RiskState, WeeklyScanState
)


class Signal:
    """
    Represents a trading signal generated by a BTC trigger.
    """
    def __init__(self, trigger_time_ist: str, side: str,
                 btc_return_pct: float, btc_close: float,
                 entry_price: float, tp_price: float, sl_price: float,
                 coin: str):
        self.trigger_time_ist = trigger_time_ist
        self.side = side  # 'LONG' or 'SHORT'
        self.btc_return_pct = btc_return_pct
        self.btc_close = btc_close
        self.entry_price = entry_price
        self.tp_price = tp_price
        self.sl_price = sl_price
        self.coin = coin
    
    def __repr__(self):
        return (f"Signal({self.trigger_time_ist} | {self.side} {self.coin} "
                f"| BTC={self.btc_return_pct:+.2f}% "
                f"| Entry={self.entry_price:.6f} "
                f"| TP={self.tp_price:.6f} SL={self.sl_price:.6f})")


class SignalGenerator:
    """
    Analyzes BTC 1H candles and generates trading signals.
    """
    
    def __init__(self):
        self.client = get_data_client()
    
    def get_latest_btc_candle(self) -> Optional[dict]:
        """
        Get the most recent COMPLETED BTC 1H candle.
        We check for the candle that closed at xx:30 IST.
        
        Returns:
            Candle dict with keys: ts, o, h, l, c, v
            Or None if unable to fetch.
        """
        try:
            # Fetch last 3 candles to ensure we get the completed one
            candles = self.client.get_klines('BTCUSDT', '1h', limit=3)
            if not candles:
                return None
            return candles[-2]  # Second-to-last is the most recent completed candle
        except Exception as e:
            log_event('ERROR', 'signal', f"Failed to fetch BTC candle: {e}")
            return None
    
    def check_trigger(self) -> Optional[Signal]:
        """
        Check if the latest BTC candle triggered a signal.
        
        Logic:
        1. Get latest completed BTC 1H candle
        2. Check if it wasn't already processed
        3. Calculate BTC return vs previous candle
        4. If |BTC return| > BTC_TRIGGER_PCT, generate signal for each trading coin
        
        Returns:
            Signal object if triggered, None otherwise.
        """
        # Get latest completed candle
        candle = self.get_latest_btc_candle()
        if not candle:
            return None
        
        candle_ts = candle['ts']
        candle_close_ist = to_ist_timestamp(candle_ts)
        
        # Check if already processed (prevents duplicate triggers)
        if PositionState.is_btc_candle_processed(candle_close_ist):
            return None
        
        # Get previous candle for return calculation
        prev_candle_ts = candle_ts - 3600000  # 1 hour earlier
        try:
            prev_candle = self.client.get_klines(
                'BTCUSDT', '1h',
                start_time=prev_candle_ts,
                limit=1
            )
            if not prev_candle:
                log_event('WARNING', 'signal', f"No previous candle found for {candle_close_ist}")
                return None
            prev_close = prev_candle[0]['c']
        except Exception as e:
            log_event('ERROR', 'signal', f"Failed to fetch previous BTC candle: {e}")
            return None
        
        # Calculate BTC return
        btc_return = (candle['c'] - prev_close) / prev_close * 100
        
        # Mark candle as processed (even if no trigger - don't re-check)
        PositionState.mark_btc_candle_processed(candle_close_ist)
        
        # Check trigger condition
        if abs(btc_return) < BTC_TRIGGER_PCT:
            return None
        
        side = 'LONG' if btc_return > 0 else 'SHORT'
        
        log_event('INFO', 'signal',
                  f"TRIGGER: BTC {btc_return:+.2f}% at {candle_close_ist} ({side})")
        
        # We generate the signal but don't choose which coin here
        # The caller (trading engine) decides which coin(s) to trade
        return Signal(
            trigger_time_ist=candle_close_ist,
            side=side,
            btc_return_pct=btc_return,
            btc_close=candle['c'],
            entry_price=0.0,  # Will be filled per-coin
            tp_price=0.0,
            sl_price=0.0,
            coin='',  # Will be filled per-coin
        )
    
    def get_entry_prices(self, signal: Signal, coins: list) -> dict:
        """
        Get entry prices for a list of coins at the signal time.
        
        Args:
            signal: The trigger signal
            coins: List of coin symbols (e.g., ['FARTCOINUSDT', 'ETHUSDT'])
        
        Returns:
            Dict of coin_symbol -> {'entry': price, 'tp': price, 'sl': price}
        """
        # Get the candle at the trigger time for each coin
        # The trigger time is the candle close time
        # We need to find the 1H candle for each coin at that time
        
        trigger_ts = 0
        # Convert IST trigger time back to UTC timestamp
        try:
            from datetime import datetime
            ist_dt = datetime.strptime(signal.trigger_time_ist, "%Y-%m-%d %H:%M:%S")
            utc_dt = ist_dt - timedelta(hours=5.5)
            trigger_ts = int(utc_dt.timestamp() * 1000)
        except Exception as e:
            log_event('ERROR', 'signal', f"Failed to parse trigger time: {e}")
            return {}
        
        result = {}
        for coin in coins:
            try:
                # Fetch the candle at the trigger time
                candle = self.client.get_klines(
                    coin, '1h',
                    start_time=trigger_ts,
                    limit=1
                )
                if not candle:
                    log_event('WARNING', 'signal', f"No candle for {coin} at trigger time")
                    continue
                
                entry_price = candle[0]['c']
                
                if signal.side == 'LONG':
                    tp_price = entry_price * (1 + TP_PCT / 100)
                    sl_price = entry_price * (1 - SL_PCT / 100)
                else:
                    tp_price = entry_price * (1 - TP_PCT / 100)
                    sl_price = entry_price * (1 + SL_PCT / 100)
                
                result[coin] = {
                    'entry': entry_price,
                    'tp': tp_price,
                    'sl': sl_price,
                    'side': signal.side,
                }
            except Exception as e:
                log_event('ERROR', 'signal', f"Failed to get entry for {coin}: {e}")
        
        return result
    
    def get_filtered_coins(self) -> list:
        """
        Get the list of coins to trade (fixed + dynamic from weekly scan).
        Applies volume/correlation filter based on weekly scan results.
        """
        return WeeklyScanState.get_trading_coins()


# ─── Verify Signal Against Backtest ────────────────────────

def verify_signal_against_backtest(btc_candle_ts: int,
                                    btc_prev_close: float) -> dict:
    """
    Verify that the signal generator produces the same result as our backtest.
    Used for testing only.
    
    Args:
        btc_candle_ts: The candle timestamp (ms)
        btc_prev_close: Previous BTC candle close price
    
    Returns:
        Dict with signal info or error
    """
    client = get_data_client()
    try:
        candle = client.get_klines('BTCUSDT', '1h',
                                    start_time=btc_candle_ts, limit=1)
        if not candle:
            return {'error': 'No candle found'}
        
        c = candle[0]
        btc_ret = (c['c'] - btc_prev_close) / btc_prev_close * 100
        
        return {
            'ts': c['ts'],
            'open': c['o'],
            'close': c['c'],
            'high': c['h'],
            'low': c['l'],
            'btc_return_pct': round(btc_ret, 2),
            'trigger': abs(btc_ret) >= 1.0,
            'side': 'LONG' if btc_ret > 0 else 'SHORT' if abs(btc_ret) >= 1.0 else 'NONE',
        }
    except Exception as e:
        return {'error': str(e)}
